version: '3.7'

services:
  frontend:
    build:
      context: ./frontend
    image: frontend
    container_name: frontend
    networks:
      - network
    depends_on:
      - application
  application:
    build:
      context: ./application
    image: application
    container_name: application
    networks:
      - network
    depends_on:
      - database
      - redis
  database:
    build:
      context: ./database
    image: database
    container_name: database
    networks:
      - network
  redis:
    build:
      context: ./redis
    image: redis
    container_name: redis
    networks:
      - network
networks:
  network:
    ipam:
      config:
        - subnet: 172.20.16.0/24
volumes:
  httpd: