version: '3.7'

services:
  httpd1:
    image: httpd:2.4.46
    container_name: httpd1
    volumes:
      - ./files/httpd1/server.crt.pem:/etc/httpd/ssl/server.crt.pem:ro
      - ./files/httpd1/server.key.pem:/etc/httpd/ssl/server.key.pem:ro
      - ./files/httpd1/httpd.conf:/usr/local/apache2/conf/httpd.conf:ro
    networks:
      - ejbca
  ejbca1:
    image: primekey/ejbca-ce:6.15.2.6
    container_name: ejbca1
    environment:
      HOSTNAME: ejbca0
      TLS_SETUP_ENABLED: simple
      PROXY_AJP_BIND: 0.0.0.0
      DATABASE_USER: ejbca
      DATABASE_PASSWORD: ejbca
      DATABASE_JDBC_URL: jdbc:postgresql://postgres1/ejbca
    networks:
      - ejbca
  ejbca2:
    image: primekey/ejbca-ce:6.15.2.6
    container_name: ejbca2
    environment:
      HOSTNAME: ejbca1
      TLS_SETUP_ENABLED: simple
      PROXY_AJP_BIND: 0.0.0.0
      DATABASE_USER: ejbca
      DATABASE_PASSWORD: ejbca
      DATABASE_JDBC_URL: jdbc:postgresql://postgres1/ejbca
    networks:
      - ejbca
  postgres1:
    image: postgres:12.3
    container_name: postgres1
    environment:
      POSTGRES_PASSWORD: ejbca
      POSTGRES_USER: ejbca
      POSTGRES_DB: ejbca
      POSTGRES_HOST_AUTH_METHOD: md5
    networks:
      - ejbca
    depends_on:
      - ejbca1
      - ejbca2
networks:
  ejbca:
    ipam:
      config:
        - subnet: 172.20.15.0/24