version: '3.7'

services:
  keycloak:
    container_name: keycloak
    build:
      context: ./jboss-keycloak
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      PROXY_ADDRESS_FORWARDING: "true"
      KEYCLOAK_IMPORT: /tmp/realm.json
    networks:
      mosquitto:
        ipv4_address: 172.20.16.10
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:1.6.10
    ports:
      - "1883:1883"
    networks:
      - mosquitto
  node-red:
    container_name: node-red
    build:
      context: ./node-red
    ports:
      - "1880:1880"
    environment:
      RED_HOST: 0.0.0.0
      RED_PORT: 1880
    networks:
      mosquitto:
        ipv4_address: 172.20.16.40
    depends_on:
      - mosquitto
      - keycloak
  sonarqube:
    container_name: sonarqube
    build:
      context: ./sonarqube
    networks:
      mosquitto:
        ipv4_address: 172.20.16.30
    depends_on:
      - keycloak
  grafana:
    container_name: grafana
    build:
      context: ./grafana
    networks:
      mosquitto:
        ipv4_address: 172.20.16.20
    depends_on:
      - keycloak
networks:
  mosquitto:
    ipam:
      config:
        - subnet: 172.20.16.0/24
