version: '3.7'

services:
  freeipa-server:
    build:
      context: ./freeipa-server
    image: freeipa-server
    container_name: freeipa-server
    networks:
      - network
#    volumes:
#      - apache201-log-volume:/var/log/apache2:rw
#    depends_on:
#      - rails01

networks:
  network:
    ipam:
      config:
        - subnet: 172.20.15.0/24

volumes:
  example-volume: