version: '3.7'

services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    container_name: es01
    environment:
      - node.name=es01
      - node.master=true
      - node.voting_only=false
      - node.data=true
      - node.ingest=true
      - node.ml=true
      - node.transform=true
      - xpack.transform.enabled=true
      - xpack.ml.enabled=true
      - node.remote_cluster_client=false
      - cluster.name=cluster
      - discovery.seed_hosts=es01
      - cluster.initial_master_nodes=es01
      - bootstrap.memory_lock=true
      - xpack.monitoring.collection.enabled=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - elasticsearch
  ls01-shipper:
    image: docker.elastic.co/logstash/logstash:7.7.0
    container_name: ls01-shipper
    networks:
      - elasticsearch
    volumes:
      - ./files/logstash-shipper/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./files/logstash-shipper/pipeline/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
    depends_on:
      - kafka01
  ls01-indexer:
    image: docker.elastic.co/logstash/logstash:7.7.0
    container_name: ls01-indexer
    networks:
      - elasticsearch
    volumes:
      - ./files/logstash-indexer/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./files/logstash-indexer/pipeline/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
    depends_on:
      - es01
      - kafka01
  zoo1:
    image: zookeeper
    container_name: zoo1
    environment:
      MYID: 1
      SERVERS: zoo1
    networks:
      - elasticsearch
  kafka01:
    image: wurstmeister/kafka
    container_name: kafka01
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS: PLAINTEXT://kafka01:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka01:9092
      KAFKA_ADVERTISED_HOST_NAME: kafka01
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_LOG_RETENTION_HOURS: "168"
      KAFKA_LOG_RETENTION_BYTES: "100000000"
      KAFKA_ZOOKEEPER_CONNECT:  zoo1:2181
      KAFKA_CREATE_TOPICS: "log:3:3"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    networks:
      - elasticsearch
    volumes:
      - kafka01-volume:/kafka
    depends_on:
      - zoo1
  kibana:
    image: docker.elastic.co/kibana/kibana:7.7.0
    container_name: kibana
    environment:
      SERVER_NAME: kibana
      SERVER_HOST: kibana
      ELASTICSEARCH_HOSTS: '["http://es01:9200"]'
    networks:
      - elasticsearch
    depends_on:
      - es01
  fb01:
    image: docker.elastic.co/beats/filebeat:7.7.0
    container_name: fb01
    environment:
      LOGSTASH_HOSTS: '["ls01-shipper:5044"]'
    volumes:
      - ./files/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./files/filebeat/modules.d/apache.yml:/usr/share/filebeat/modules.d/apache.yml:ro
      - httpd01-volume:/var/log/apache2:ro
    command: ["--strict.perms=false"]
    networks:
      - elasticsearch
    depends_on:
      - ls01-shipper
      - httpd01
  httpd01:
    image: httpd:2.4.43
    container_name: httpd01
    volumes:
      - httpd01-volume:/var/log/apache2
      - ./files/httpd/httpd.conf:/usr/local/apache2/conf/httpd.conf:ro
    networks:
      - elasticsearch
networks:
  elasticsearch:
    ipam:
      config:
        - subnet: 172.20.15.0/24
volumes:
  httpd01-volume:
  kafka01-volume: